#!/bin/sh

stop_ap() {
	/sbin/start-stop-daemon -K -q -p /var/run/udhcpd-ap.pid
	/sbin/start-stop-daemon -K -q -p /var/run/hostapd.pid
	rm -f /var/run/udhcpd-ap.pid /var/run/hostapd.pid
	/sbin/ifconfig wlan0 down

	# Explicitely call the "ledblink" script to stop
	# the LED from blinking.
	/usr/bin/env IFACE=wlan0 /etc/network/if-post-down.d/ledblink
}

start_ap() {
	/sbin/ifconfig wlan0 inet 10.1.2.1 netmask 255.255.255.0
	ERR=$?
	[ $ERR -eq 0 ] || exit $ERR

	/usr/sbin/hostapd -P /var/run/hostapd.pid -B $CONFFILE > /dev/null
	ERR=$?
	[ $ERR -eq 0 ] || exit $ERR

	/sbin/start-stop-daemon -S -q -b -m -p /var/run/udhcpd-ap.pid \
		-x /usr/sbin/udhcpd -- -f -S /etc/udhcpd-ap.conf

	# Explicitely call the "ledblink" script; we want to blink
	# the LED on AP mode too.
	/usr/bin/env IFACE=wlan0 /etc/network/if-up.d/ledblink
}

CONFFILE=/usr/local/etc/hostapd-ap.conf
if [ ! -f $CONFFILE ] ; then
	MAC=`cat /sys/class/net/wlan0/address | sed 's/://g' `
	echo "interface=wlan0
ssid=gcwzero-$MAC
wpa=2
wpa_passphrase=$MAC
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
hw_mode=g
channel=10" > $CONFFILE
fi

case "$1" in
	--start)
		start_ap
		;;
	--stop)
		stop_ap
		;;
	*)
		echo "Usage: ap [--start|--stop]"
		;;
esac
