#!/bin/sh

export HOME=`cat /etc/passwd |head -1 |cut -d':' -f 6`

# Restore the framebuffer to a working state
/usr/sbin/unlockvt > /dev/null

# Disactivate the console on framebuffer
echo 0 > /sys/devices/virtual/vtconsole/vtcon1/bind

# Restore the regular key map
if [ -f /sys/module/linkdev/parameters/alt_key_map ] ; then
	echo N > /sys/module/linkdev/parameters/alt_key_map
fi

if [ -f /usr/local/sbin/frontend_start ]; then
	exec /usr/local/sbin/frontend_start
else
	exec /usr/bin/gmenu2x
fi
