#!/bin/sh

if [ "$SUBSYSTEM" != "block" ]; then
    echo "WARNING: trying to mount a non-block device!"

elif [ "$ACTION" = "remove" ]; then
    if [ `mount |grep "$1 "` ]; then
        echo "WARNING: SD card pulled out without unmounting first!"
        umount -f /dev/$1
    fi
    rmdir /media/$1

elif ! [ `ls /sys/class/block/${1}?* 2>/dev/null` ]; then
    mkdir /media/$1 && ( mount /dev/$1 /media/$1 -o $2 || rmdir /media/$1 )

fi
