#!/bin/sh

if [ "$SUBSYSTEM" != "block" ]; then
    echo "Refusing to mount non-block device: $1"
    exit 1
fi

DEV="/dev/$1"

if [ "$1" = "mmcblk1p1" ]; then
    MNT="/media/sdcard"
elif [ "$1" = "mmcblk0p1" ]; then
    if ! [ -f /etc/local/mount_system ]; then
        exit 0
    fi
    MNT="/media/system"
elif [ "$1" = "mmcblk0p2" ]; then
    MNT="/media/data"
else
    MNT="/media/$1"
fi

if [ "$ACTION" = "remove" ]; then
    if [ `mount |grep "$DEV "` ]; then
        echo "WARNING: SD card pulled out without unmounting first!"
        umount -f $DEV
    fi
    rmdir $MNT

elif ! [ `ls /sys/class/block/${1}?* 2>/dev/null` ]; then
    mkdir $MNT && ( mount $DEV $MNT -o $2 || rmdir $MNT )

fi
