#!/bin/sh

. /etc/tvout.conf

if [ -f /etc/local/tvout.conf ]; then
	. /etc/local/tvout.conf
fi

ACTION=$1

if [ "$ACTION" = "--toggle" ]; then
	if [ "`cat /sys/devices/platform/jz4740-fb/tv_out`" = "off" ]; then
		ACTION="--on"
	else
		ACTION="--off"
	fi
fi

if [ "$ACTION" = "--on" ]; then
	amixer set Speaker off
	echo "$TV_VSYNC" > /sys/devices/platform/jz4740-fb/tv_out_vsync
	tvout --$TV_NORM

elif [ "$ACTION" = "--off" ]; then
	tvout --off
	amixer set Speaker on
fi
