#!/bin/sh

case "$IFACE" in
	wlan[0-9])
		;;
	*)
		exit 0
		;;
esac

CONF_FILE=/etc/local/network/config-${IFACE}.conf

[ -f $CONF_FILE ] || exit 1
. $CONF_FILE

case "$WLAN_ENCRYPTION" in
	wep)
		echo "network={
			nssid=\"$WLAN_ESSID\"
			nscan_ssid=1
			npriority=5
			nkey_mgmt=NONE
			nwep_key0=\"$WLAN_PASSPHRASE\"
			nwep_tx_keyidx=0
		}" > /tmp/.${IFACE}_config
		;;

	wpa|wpa2)
		/usr/sbin/wpa_passphrase \
			"$WLAN_ESSID" "$WLAN_PASSPHRASE" > /tmp/.${IFACE}_config
		;;

	none)
		;;

	*)
		exit 1
esac

/sbin/ifconfig "$IFACE" up
/sbin/iwconfig "$IFACE" mode "$WLAN_MODE" essid "$WLAN_ESSID"
RET=$?

if [ "$WLAN_ENCRYPTION" != "none" ] ; then
	if [ -f "/var/run/wpa_supplicant_${IFACE}.pid" ] ; then
		/sbin/start-stop-daemon -K -q -p /var/run/wpa_supplicant_${IFACE}.pid
	fi

	/usr/sbin/wpa_supplicant -B -D "$WLAN_DRIVER" -i "$IFACE" \
		-c /tmp/.${IFACE}_config -P /var/run/wpa_supplicant_${IFACE}.pid
	RET=$?
fi

exit $RET
